#!/bin/bash
#Menu

echo -e "================================================="
echo -e ""  
echo -e "> menu         : menampilkan daftar perintah"
echo -e "> usernew      : membuat akun SSH & OpenVPN"
echo -e "> trial        : membuat akun trial"
echo -e "> hapus        : menghapus akun SSH & OpenVPN"
echo -e "> cek          : cek user login"
echo -e "> member       : daftar member SSH & OpenVPN"
echo -e "> userlimit    : Limit login Dropbear"
echo -e "> userlimitssh : Limit login SSHD"
echo -e "> resvis       : restart service dropbear, webmin"
echo -e "                 squid3, OpenVPN dan SSH"
echo -e "> reboot       : reboot VPS"
echo -e "> speedtest    : speedtest VPS"
echo -e "> info         : menampilkan informasi sistem"
echo -e "> about        : info script auto install"
echo -e "> exit         : keluar dari terminal SSH"
echo -e ""
echo -e "================================================="
