#!/bin/bash

echo -e "================================================="
echo -e ""  
echo -e "> menu         : Menampilkan daftar perintah"
echo -e "> usernew      : Membuat akun SSH & OpenVPN"
echo -e "> trial        : Membuat akun trial"
echo -e "> hapus        : Menghapus akun SSH & OpenVPN"
echo -e "> cek          : Cek user login"
echo -e "> member       : Daftar member SSH & OpenVPN"
echo -e "> userlimit    : Limit login Dropbear"
echo -e "> userlimitssh : Limit login SSHD"
echo -e "> resvis       : Restart service dropbear, webmin"
echo -e "                 squid3, OpenVPN dan SSH"
echo -e "> reboot       : Reboot VPS"
echo -e "> speedtest    : Speedtest VPS"
echo -e "> info         : Menampilkan informasi sistem"
echo -e "> about        : Info script auto install"
echo -e "> exit         : Keluar dari terminal SSH"
echo -e ""
echo -e "================================================="
